### ISSUE TITLE
Preparing a Dataset for Model Prediction

### ISSUE THREAD

**Issue by hl2500** [deepchem/DeepLearningLifeSciences#13]
Hello, I'm working on the predictive model in Chapter 11, but could not find the rd_filters.py and associated data files here (suggested by the book). Does anyone have idea where I can find them? Thank you!

**Comment by peastman** [comment]
I checked with Pat, and he's going to add the missing files to this repository.  Sorry they got missed!

**Comment by hl2500** [comment]
Okay, Thank you!

**Comment by peastman** [comment]
All the code for chapter 11 is now in.

**Comment by PatWalters** [comment]
rd_filters.py is available at https://github.com/PatWalters/rd_filters
