### ISSUE TITLE
Chapter 11, leftover active decoys

### ISSUE THREAD

**Issue by altayg** [deepchem/DeepLearningLifeSciences#15]
Did you forget to drop the leftover active decoy molecules or did you left them as is deliberately?

After this ratio check, there is no further dropping for the 12 leftover active decoys:

charged = revised_decoy_df[revised_decoy_df["charge"] != 0]
charged.shape[0]/revised_decoy_df.shape[0]  # 0.00263

charged.shape[0]  # 12

**Comment by PatWalters** [comment]
The active molecules and decoy molecules are two different sets.  The
reason that there are a few charged molecules left in the set is that
the NeutraliseCharges function does not have the appropriate SMARTS
patterns for neutralization of all of the molecules.  When I looked at the
12 structures, it was either functionality like N-oxides or what appears to
be incorrect structures from the DUD-E database.

Pat

**Comment by altayg** [comment]
Would it not be better to remove them and not include in the model?

**Comment by PatWalters** [comment]
Probably, although I don't think it would make that much of a difference.

Pat
