### ISSUE TITLE
Chapter7 issue

### ISSUE THREAD

**Issue by partrita** [deepchem/DeepLearningLifeSciences#6]
```
this model can be used to make predictions out of the box. There are directions on downloading the pretrained model in the code repository associated with the book (https://github.com/deepchem/DeepLearningLifeSciences).
```

there is no pretrained model in code repository

**Comment by rbharath** [comment]
@partrita Good find; this slipped through the cracks somehow. I'll keep this issue open and work on getting the model in place within the next couple weeks.

**Comment by partrita** [comment]
> 
> 
> @partrita Good find; this slipped through the cracks somehow. I'll keep this issue open and work on getting the model in place within the next couple weeks.

Thanks
